### PR TITLE
Jingle Bell Relay Problems

### PR DESCRIPTION
**Pull request by JJ27**
Josh Joseph

Jingle Bell Relays(problems 1-5)
Chapter 11

Original Problem by Christopher Haver, Computer Science Teacher at SBHS in NJ
Solutions written by me(Josh Joseph)

5 problems that get progressively more difficult from 1-5. When you get the correct answer, a "You win" graphic appears.

### CODE REVIEW

**Review by ARajan1084 — APPROVED** [review]
Wow that is a lot of practice problems

**Review by AlveeraMunshi — APPROVED** [review]
all have same, correct output as intended so your good and the linting looks fine as far as I know

**Comment by phrdang** [comment]
@JJ27 You may want to check the output for the Java (Checkstyle) check so that you can merge. Let @abhatia1205 (Anant) know if it the warnings are overkill, if so he should use his admin privileges to merge manually.

**Comment by abhatia1205** [comment]
Awesome practice problems and the formatting looks good enough, so I'm gonna go ahead and merge!

**Pull request merged**
