### PR TITLE
isPrime Problem

### PR DESCRIPTION
**Pull request by JJ27**
Josh Joseph
Prime Practice
Chapter 13 Advanced Recursion

Simple Prime Number Check

I think the sqrt(n) thing is as advanced as we need to go with this since anything more might be beyond the scope of this course.

Also added Advanced and Ch. 13 folders to the repository.

### CODE REVIEW

**Review by AlveeraMunshi — APPROVED** [review]
Great problem, it works :))

**Comment by JJ27** [comment]
@phrdang @ARajan1084 
It seems to me that the GitHub Actions Bot doesn't seem to agree with the changes that the Prettify Bot is making.

**Comment by phrdang** [comment]
> It seems to me that the GitHub Actions Bot doesn't seem to agree with the changes that the Prettify Bot is making.

Oops, sorry I forgot that the PR I made #12 never got merged. That should eliminate some of the excess errors.

**Review by phrdang — APPROVED** [review]
Looks great, thanks for the problem!

**Pull request merged**
